fake error

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -13,4 +13,8 @@ jobs:
      - run: echo "Job's status is ${{ job.status }}"
 
 
-
+- name: Faking an error
+       run: |
+         echo "Before faking an error"
+         exit 1
+         echo "After faking an error"
